export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST'
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE'

export const USERS_CANDIDATE = 'USERS_CANDIDATE'
export const USERS_EMPLOYER = 'USERS_EMPLOYER'
export const USERS_LOGOUT = 'USERS_LOGOUT'

export const FETCH_JOBS_REQUEST = 'FETCH_JOBS_REQUEST'
export const FETCH_JOBS_SUCCESS = 'FETCH_JOBS_SUCCESS'
export const FETCH_JOBS_FAILURE = 'FETCH_JOBS_FAILURE'